config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :water_sensors
  resources :solo_sensors
  resources :monitoring_histories
  resources :tanks
  resources :food_species
  resources :foods
  resources :food_types
  resources :ambiental_conditions
  resources :dashboards, only: :index
  scope :admin do
    get "/", to: "admin#index", as: "alarms"
    get "/new", to: "admin#new", as: "new_alarm"
    get "/:id", to: "admin#edit", as: "edit_alarm"
    post "/", to: "admin#create"
    patch ".:id", to: "admin#update"
  end
  get "/users/new", to: "users#new"
  get "/users", to: "users#index"
  get "/species", to: "species#index", as: "species"
  get "/species/new", to: "species#new", as: "new_specie"
  get "/species/edit/:id", to: "species#edit", as: "edit_species"
  post "/species", to: "species#create"
  patch "/species.:id", to: "species#update"
  delete "/species.:id", to: "species#destroy"
  post "/tanks/find_date", to: "tanks#find_date"
  post "/ambiental_conditions/calc", to: "ambiental_conditions#calculate"
  post "/notifications/update_view/:id", to: "notifications#update_view"
  post "/dashboards/ambiental_condition_values", to: "dashboards#get_ambiental_condition_values"
  post "/dashboards/tank_values", to: "dashboards#get_tank_values"
  post "/dashboards/ambiental_and_tank_values", to: "dashboards#get_difference_between_ambiental_condition_and_tank_values"
  post "/feed/:id", to: "tanks#feed"
  post "/check_alarms", to: "admin#catch_alarm"
  post "/dados_diarios", to: "tanks#insert_diary_data"
  post "/users/create", to: "users#create"
  redirect("/users/sign_in")

  authenticate :user do
    root to: "dashboards#index"
  end
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :alarm_type
end

app/models/alarm_type.rb
class AlarmType < ApplicationRecord
  has_many :alarms

  def to_s
    description
  end
end

app/models/ambiental_condition.rb
class AmbientalCondition < ApplicationRecord
  validates :ideal_acidity, presence: true
  validates :ideal_temperature, presence: true
  validates :ideal_oxigen, presence: true
  validates :ideal_ammonia, presence: true
  validates :ideal_ph, presence: true

  belongs_to :specie


  def to_s
    "temp: #{ideal_temperature} - O²: #{ideal_oxigen} - amonia: #{ideal_ammonia} - acidez: #{ideal_acidity}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_specie.rb
class FoodSpecie < ApplicationRecord
  belongs_to :food_type

  validates :name, presence: true
  validates :composition, presence: true
  validates :food_quantity, presence: true

  def to_s
    name
  end
end

app/models/food_type.rb
class FoodType < ApplicationRecord
  validates :description, presence: true

  def to_s
    description
  end
end

app/models/monitoring_history.rb
class MonitoringHistory < ApplicationRecord
  belongs_to :tank

  validates :liming, presence: true
  validates :oxigen, presence: true
  validates :ph, presence: true
  validates :quantitiy_food_daily, presence: true
  validates :quantity_fetilizing, presence: true
  validates :monitoring_date, presence: true

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :tank
end

app/models/perfil.rb
class Perfil < ApplicationRecord
  def to_s
    description
  end
end

app/models/solo_sensor.rb
class SoloSensor < ApplicationRecord
  belongs_to :tank
end

app/models/specie.rb
class Specie < ApplicationRecord
  belongs_to :food_specie
  has_one :ambiental_condition

  include RemoveSpecialCharacters

  validates :specie_name, presence: true
  validates :price, presence: true
  validates :weight, presence: true

  validate :no_price

  def to_s
    specie_name
  end

  def no_price
    errors.add(:price, "Valor R$0,00 não pode ser adicionado") if price == "000"
  end

end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :user
  belongs_to :specie

  has_many :notifications

  include RemoveSpecialCharacters

  validates :population_date, presence: true
  validates :initial_quantity, presence: true

  def to_s
    tank_type
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :perfil

  def to_s
    cpf
  end

end

app/models/water_sensor.rb
class WaterSensor < ApplicationRecord
  belongs_to :tank
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    notification = ''
    [:success, :info, :warning, :error].each do |type|
      if flash[type]
        notification += "<script>notification('#{type}', '#{flash[type]}');</script>"
      end
    end
    notification.html_safe
  end

end

app/helpers/food_species_helper.rb
module FoodSpeciesHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/admin/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Criar Alarme</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Alarme</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">cadastrar</a>
          </li>
        </ul>
      </div>
      <div class="tile">
        <%= simple_form_for(@alarm) do |f| %>
          <div class="row">
            <div class="col-md-4">
              <%= f.input :message, label: "Menssagem", input_html: {class: "form-control"}, error: "Mensagem é obrigatório" %>
            </div>
            <div class="col-md-4">
              <%= f.association :alarm_type, label: "Tipo do alarme", input_html: {class: "form-control"}, include_blank: "Selecione", error: "Tipo do alarme não pode ficar em branco" %>
            </div>
            <div class="col-md-2">
              <b>Ativo?</b>
              <div class="toggle-flip">
                <label>
                  <input type="checkbox" name="alarm[active]" id="food_type_active"><span class="flip-indecator" data-toggle-on="ON" data-toggle-off="OFF"></span>
                </label>
              </div>
            </div>
            <div class="col-md-2">
              <b>Efeito de som?</b>
              <div class="toggle-flip">
                <label>
                  <input type="checkbox" name="alarm[sound_effect]" id="food_type_active"><span class="flip-indecator" data-toggle-on="ON" data-toggle-off="OFF"></span>
                </label>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= button_tag(type: "submit", class: "btn btn-primary pull-right") do %>
                <i class="fa fa-save"></i>
                <span>Salvar</span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/admin/edit.html.erb
<%= render "form", alarm: @alarm %>

app/views/admin/index.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Listar Condições Ambientais</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Condições Ambientais</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">listar</a>
          </li>
        </ul>
      </div>

      <div class="tile">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Tipo do Alarme</th>
            <th>Ativo?</th>
            <th>Efeito de som? </th>
            <th colspan="3"></th>
          </tr>
          </thead>
          <% @alarms.each do |alarm| %>
            <tr>
              <td><%= alarm.alarm_type %></td>
              <td>
                <% if alarm.active? %>
                  Sim
                <% else %>
                  Não
                <% end %>
              </td>
              <td>
                <% if alarm.sound_effect? %>
                  Sim
                <% else %>
                  Não
                <% end %>
              </td>
              <td>
                <%= link_to "<i class='fa fa-edit'></i><span> Editar</span>".html_safe, edit_alarm_path(alarm), class: "btn btn-outline-primary" %>
              </td>
            </tr>
          <% end %>
          <tbody>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<aside class="app-sidebar" data-turbolinks="false">
  <div class="app-sidebar__user">
    <div style="font-size: 45px;">
      <i class="fa fa-user"></i>
    </div>
    <div>
      <p class="app-sidebar__user-name" style="margin-left: 10px;"><%= current_user.name %></p>
      <p class="app-sidebar__user-designation cpf" style="margin-left: 10px;"><%= current_user.cpf %></p>
    </div>
  </div>
  <ul class="app-menu" data-turbolinks="false">
    <li>
      <a class="app-menu__item" href="/">
        <i class="app-menu__icon fa fa-dashboard"></i>
        <span class="app-menu__label">Dashboard</span>
      </a>
    </li>

    <% if current_user.perfil_id == 1 || current_user.perfil_id == 3 %>
      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa fa-list-ul"></i>
          <span class="app-menu__label">Tipos de Ração</span>
          <i class="treeview-indicator fa fa-angle-right"></i></a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/food_types">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/food_types/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>

      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa-file-text"></i>
          <span class="app-menu__label">Ração da Espécie</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/food_species">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/food_species/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>

      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa fa-th-large"></i>
          <span class="app-menu__label">Espécies</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/species">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/species/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>
    <% end %>

    <li class="treeview">
      <a class="app-menu__item" href="#" data-toggle="treeview">
        <i class="app-menu__icon fa fa-shower"></i>
        <span class="app-menu__label">Tanques</span>
        <i class="treeview-indicator fa fa-angle-right"></i>
      </a>
      <ul class="treeview-menu">
        <li>
          <a class="treeview-item" href="/tanks">
            <i class="icon fa fa-circle-o"></i>
            <span>Listar</span>
          </a>
        </li>
        <li>
          <a class="treeview-item" href="/tanks/new">
            <i class="icon fa fa-circle-o"></i>
            <span>Criar</span>
          </a>
        </li>
      </ul>
    </li>


    <% if current_user.perfil_id == 1 || current_user.perfil_id == 3 %>

      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa fa-area-chart"></i>
          <span class="app-menu__label">Monitoramento</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/monitoring_histories">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/monitoring_histories/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>

      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa-snowflake-o"></i>
          <span class="app-menu__label">Condição Ambiental</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/ambiental_conditions">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/ambiental_conditions/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>

      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa-unlock-alt"></i>
          <span class="app-menu__label">Painel Administrativo</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/admin">
              <i class="icon fa fa-circle-o"></i>
              <span>Listar</span>
            </a>
          </li>
          <li>
            <a class="treeview-item" href="/admin/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Criar</span>
            </a>
          </li>
        </ul>
      </li>
    <% end %>

    <% if current_user.perfil_id == 3 %>
      <li class="treeview">
        <a class="app-menu__item" href="#" data-toggle="treeview">
          <i class="app-menu__icon fa fa-black-tie"></i>
          <span class="app-menu__label">Usuários</span>
          <i class="treeview-indicator fa fa-angle-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <a class="treeview-item" href="/users/new">
              <i class="icon fa fa-circle-o"></i>
              <span>Adicionar</span>
            </a>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
</aside>

app/views/shared/_topbar.html.erb
<header class="app-header"><a class="app-header__logo" href="/">Águas Tranquilas</a>
  <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>

  <ul class="app-nav">
    <li class="app-search">
      <input class="app-search__input" type="search" placeholder="Search">
      <button class="app-search__button"><i class="fa fa-search"></i></button>
    </li>

    <li class="dropdown">
      <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><span class="badge badge-light"><%= @notifications.length %></span><i class="fa fa-bell-o fa-lg"></i></a>
      <ul class="app-notification dropdown-menu dropdown-menu-right">
        <% if @notifications.nil? %>
          <div class="app-notification__content">
            <li>
              <a class="app-notification__item" href="javascript:;">
                <span class="app-notification__icon">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x text-success">
                    </i><i class="fa fa-eye fa-stack-1x fa-inverse"></i>
                  </span>
                </span>
                <div>
                  <p class="app-notification__message">Todas as notificações foram lidas</p>
                  <p class="app-notification__meta">Hoje</p>
                </div>
              </a>
            </li>
          </div>
        <% else %>
          <li class="app-notification__title">Você tem <%= @notifications.length %> novas notificações.</li>
          <% @notifications.each do |notification| %>
            <div class="app-notification__content">

              <% if notification.type_message == "warning" %>
                <li>
                  <a class="app-notification__item" onclick="changeViewNotification(<%= notification.id %>)">
                    <span class="app-notification__icon">
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x text-warning"></i>
                        <i class="fa fa-exclamation-triangle fa-stack-1x fa-inverse"></i>
                      </span>
                    </span>
                    <div>
                      <p class="app-notification__message"><%= notification.message %> <%= notification.tank.tank_type %></p>
                      <% if Time.now.getlocal('+00:00').strftime('%d%m%Y').to_i - notification.created_at.strftime('%d%m%Y').to_i == 0 %>
                        <p class="app-notification__meta">Hoje</p>
                      <% else %>
                        <p class="app-notification__meta">A <%= (Time.now.getlocal('+00:00').strftime('%d%m%Y').to_i - notification.created_at.strftime('%d%m%Y').to_i) / 1000 %> </p>
                      <% end %>
                    </div>
                  </a>
                </li>
              <% end %>

              <% if notification.type_message == "danger" %>
                <li>
                  <a class="app-notification__item" onclick="changeViewNotification(<%= notification.id %>)">
                    <span class="app-notification__icon">
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x text-danger"></i>
                        <i class="fa fa-times fa-stack-1x fa-inverse"></i>
                      </span>
                    </span>
                    <div>
                      <p class="app-notification__message"><%= notification.message %> <%= notification.tank.tank_type%></p>
                      <% if Time.now.getlocal('+00:00').strftime('%d%m%Y').to_i - notification.created_at.strftime('%d%m%Y').to_i == 0 %>
                        <p class="app-notification__meta">Hoje</p>
                      <% else %>
                        <p class="app-notification__meta">A <%= (Time.now.getlocal('+00:00').strftime('%d%m%Y').to_i - notification.created_at.strftime('%d%m%Y').to_i) / 1000 %> </p>
                      <% end %>
                    </div>
                  </a>
                </li>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </ul>
    </li>

    <li class="dropdown">
      <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
      <ul class="dropdown-menu settings-menu dropdown-menu-right">
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item a_black" do %>
            <i class="fa fa-sign-out fa-lg"></i>
            <span>Sair</span>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>

</header>