config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :water_sensors
  resources :solo_sensors
  resources :monitoring_histories
  resources :tanks
  resources :food_species
  resources :foods
  resources :food_types
  resources :ambiental_conditions
  resources :dashboards, only: :index
  scope :admin do
    get "/", to: "admin#index", as: "alarms"
    get "/new", to: "admin#new", as: "new_alarm"
    get "/:id", to: "admin#edit", as: "edit_alarm"
    post "/", to: "admin#create"
    patch ".:id", to: "admin#update"
  end
  get "/users/new", to: "users#new"
  get "/users", to: "users#index"
  get "/species", to: "species#index", as: "species"
  get "/species/new", to: "species#new", as: "new_specie"
  get "/species/edit/:id", to: "species#edit", as: "edit_species"
  post "/species", to: "species#create"
  patch "/species.:id", to: "species#update"
  delete "/species.:id", to: "species#destroy"
  post "/tanks/find_date", to: "tanks#find_date"
  post "/ambiental_conditions/calc", to: "ambiental_conditions#calculate"
  post "/notifications/update_view/:id", to: "notifications#update_view"
  post "/dashboards/ambiental_condition_values", to: "dashboards#get_ambiental_condition_values"
  post "/dashboards/tank_values", to: "dashboards#get_tank_values"
  post "/dashboards/ambiental_and_tank_values", to: "dashboards#get_difference_between_ambiental_condition_and_tank_values"
  post "/feed/:id", to: "tanks#feed"
  post "/check_alarms", to: "admin#catch_alarm"
  post "/dados_diarios", to: "tanks#insert_diary_data"
  post "/users/create", to: "users#create"
  redirect("/users/sign_in")

  authenticate :user do
    root to: "dashboards#index"
  end
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :alarm_type
end

app/models/alarm_type.rb
class AlarmType < ApplicationRecord
  has_many :alarms

  def to_s
    description
  end
end

app/models/ambiental_condition.rb
class AmbientalCondition < ApplicationRecord
  validates :ideal_acidity, presence: true
  validates :ideal_temperature, presence: true
  validates :ideal_oxigen, presence: true
  validates :ideal_ammonia, presence: true
  validates :ideal_ph, presence: true

  belongs_to :specie


  def to_s
    "temp: #{ideal_temperature} - O²: #{ideal_oxigen} - amonia: #{ideal_ammonia} - acidez: #{ideal_acidity}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_specie.rb
class FoodSpecie < ApplicationRecord
  belongs_to :food_type

  validates :name, presence: true
  validates :composition, presence: true
  validates :food_quantity, presence: true

  def to_s
    name
  end
end

app/models/food_type.rb
class FoodType < ApplicationRecord
  validates :description, presence: true

  def to_s
    description
  end
end

app/models/monitoring_history.rb
class MonitoringHistory < ApplicationRecord
  belongs_to :tank

  validates :liming, presence: true
  validates :oxigen, presence: true
  validates :ph, presence: true
  validates :quantitiy_food_daily, presence: true
  validates :quantity_fetilizing, presence: true
  validates :monitoring_date, presence: true

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :tank
end

app/models/perfil.rb
class Perfil < ApplicationRecord
  def to_s
    description
  end
end

app/models/solo_sensor.rb
class SoloSensor < ApplicationRecord
  belongs_to :tank
end

app/models/specie.rb
class Specie < ApplicationRecord
  belongs_to :food_specie
  has_one :ambiental_condition

  include RemoveSpecialCharacters

  validates :specie_name, presence: true
  validates :price, presence: true
  validates :weight, presence: true

  validate :no_price

  def to_s
    specie_name
  end

  def no_price
    errors.add(:price, "Valor R$0,00 não pode ser adicionado") if price == "000"
  end

end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :user
  belongs_to :specie

  has_many :notifications

  include RemoveSpecialCharacters

  validates :population_date, presence: true
  validates :initial_quantity, presence: true

  def to_s
    tank_type
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :perfil

  def to_s
    cpf
  end

end

app/models/water_sensor.rb
class WaterSensor < ApplicationRecord
  belongs_to :tank
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    json = JSON.parse(params[:dados])
    User.create(name: json["name"], cpf: json["cpf"], perfil_id: json["perfil"], password: json["password"])
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :cpf, :perfil, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    notification = ''
    [:success, :info, :warning, :error].each do |type|
      if flash[type]
        notification += "<script>notification('#{type}', '#{flash[type]}');</script>"
      end
    end
    notification.html_safe
  end

end

app/helpers/food_species_helper.rb
module FoodSpeciesHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/solo_sensors_helper.rb
module SoloSensorsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Criar Usuário</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Usuário</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">cadastrar</a>
          </li>
        </ul>
      </div>
      <div class="tile">
        <%= simple_form_for(@user) do |f| %>
          <div class="row">
            <div class="col-md-6">
              <%= f.input :name, label: "Nome", input_html: {class: "form-control"}, error: "Nome não pode ficar em branco" %>
            </div>
            <div class="col-md-6">
              <%= f.input :cpf, label: "CPF", input_html: {class: "form-control cpf"}, error: "CPF não pode ficar em branco" %>
            </div>
          </div>
          <div class="row" style="margin-top: 10px;">
            <div class="col-md-6">
              <%= f.association :perfil, label: "Tipo do perfil", input_html: {class: "form-control"} %>
            </div>
            <div class="col-md-6">
              <%= f.input :password, label: "Senha", input_html: {class: "form-control"}, error: "Senha não pode ficar em branco" %>
            </div>
          </div>

          <div class="row" style="margin-top: 10px;">
            <div class="col-md-12">
              <%= button_tag(type: "button", class: "btn btn-primary pull-right btn_create_user") do %>
                <i class="fa fa-save"></i>
                <span>Salvar</span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>