config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :water_sensors
  resources :solo_sensors
  resources :monitoring_histories
  resources :tanks
  resources :food_species
  resources :foods
  resources :food_types
  resources :ambiental_conditions
  resources :dashboards, only: :index
  scope :admin do
    get "/", to: "admin#index", as: "alarms"
    get "/new", to: "admin#new", as: "new_alarm"
    get "/:id", to: "admin#edit", as: "edit_alarm"
    post "/", to: "admin#create"
    patch ".:id", to: "admin#update"
  end
  get "/users/new", to: "users#new"
  get "/users", to: "users#index"
  get "/species", to: "species#index", as: "species"
  get "/species/new", to: "species#new", as: "new_specie"
  get "/species/edit/:id", to: "species#edit", as: "edit_species"
  post "/species", to: "species#create"
  patch "/species.:id", to: "species#update"
  delete "/species.:id", to: "species#destroy"
  post "/tanks/find_date", to: "tanks#find_date"
  post "/ambiental_conditions/calc", to: "ambiental_conditions#calculate"
  post "/notifications/update_view/:id", to: "notifications#update_view"
  post "/dashboards/ambiental_condition_values", to: "dashboards#get_ambiental_condition_values"
  post "/dashboards/tank_values", to: "dashboards#get_tank_values"
  post "/dashboards/ambiental_and_tank_values", to: "dashboards#get_difference_between_ambiental_condition_and_tank_values"
  post "/feed/:id", to: "tanks#feed"
  post "/check_alarms", to: "admin#catch_alarm"
  post "/dados_diarios", to: "tanks#insert_diary_data"
  post "/users/create", to: "users#create"
  redirect("/users/sign_in")

  authenticate :user do
    root to: "dashboards#index"
  end
end

app/models/ambiental_condition.rb
class AmbientalCondition < ApplicationRecord
  validates :ideal_acidity, presence: true
  validates :ideal_temperature, presence: true
  validates :ideal_oxigen, presence: true
  validates :ideal_ammonia, presence: true
  validates :ideal_ph, presence: true

  belongs_to :specie


  def to_s
    "temp: #{ideal_temperature} - O²: #{ideal_oxigen} - amonia: #{ideal_ammonia} - acidez: #{ideal_acidity}"
  end
end

app/controllers/ambiental_conditions_controller.rb
class AmbientalConditionsController < ApplicationController
  before_action :set_ambiental_condition, only: [:show, :edit, :update, :destroy]
  before_action :redirect_perfil
  skip_before_action :redirect_perfil, only: :calculate


  def index
    @ambiental_conditions = AmbientalCondition.all
  end

  def show; end

  def new
    @ambiental_condition = AmbientalCondition.new
  end

  def edit; end

  def create
    @ambiental_condition = AmbientalCondition.new(ambiental_condition_params)

    respond_to do |format|
      if @ambiental_condition.save
        flash[:success] = "Cadastrado com sucesso"
        format.html {redirect_to ambiental_conditions_path}
        format.json {render :show, status: :created, location: @ambiental_condition}
      else
        flash[:error] = "Verifique os campos"
        format.html {render :new}
        format.json {render json: @ambiental_condition.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @ambiental_condition.update(ambiental_condition_params)
        flash[:success] = "Editado com sucesso"
        format.html {redirect_to ambiental_conditions_path}
        format.json {render :show, status: :ok, location: @ambiental_condition}
      else
        flash[:error] = "Verifique os campos"
        format.html {render :edit}
        format.json {render json: @ambiental_condition.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    respond_to do |format|

      if @ambiental_condition.destroy
        flash[:success] = "Excluído com sucesso"
        format.html {redirect_to ambiental_conditions_path}
        format.json {head :no_content}
      else
        flash[:error] = "Está relacionado em outra tabela"
        format.html {redirect_to ambiental_conditions_path}
        format.json {head :no_content}
      end
    end
  end

  def calculate
    if AmbientalCondition.all.length != 0
      tanks = Tank.all
      tanks.each do |tank|
        ambiental_condition = AmbientalCondition.find_by(specie_id: Specie.find(tank.specie_id).id)
        ammonia = tank.ammonia - ambiental_condition.ideal_ammonia
        temperature = tank.temperature - ambiental_condition.ideal_temperature
        oxigen = tank.oxigen - ambiental_condition.ideal_oxigen
        ph = tank.ph - ambiental_condition.ideal_ph
        acidity = tank.acidity - ambiental_condition.ideal_acidity
        puts ammonia
        if Notification.where(viewed: false).length == 0
          if ammonia < 0
            puts "I'M HERE"
            Notification.create(message: "Amonia está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if ammonia > 0
            Notification.create(message: "Amonia está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if temperature < 0
            Notification.create(message: "Temperatura está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if temperature < 0
            Notification.create(message: "Temperatura está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if oxigen < 0
            Notification.create(message: "Oxigenio está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if oxigen < 0
            Notification.create(message: "Oxigenio está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if ph < 0
            Notification.create(message: "PH está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if ph < 0
            Notification.create(message: "PH está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if acidity < 0
            Notification.create(message: "Acidez está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if acidity < 0
            Notification.create(message: "Acidez está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if ammonia < 0
            Notification.create(message: "Amonia está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if ammonia > 0
            Notification.create(message: "Amonia está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if temperature < 0
            Notification.create(message: "Temperatura está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if temperature < 0
            Notification.create(message: "Temperatura está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if oxigen < 0
            Notification.create(message: "Oxigenio está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if oxigen < 0
            Notification.create(message: "Oxigenio está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if ph < 0
            Notification.create(message: "PH está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if ph < 0
            Notification.create(message: "PH está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

          if acidity < 0
            Notification.create(message: "Acidez está menor do que o ideal no", type_message: "danger", tank_id: tank.id)
          end
          if acidity < 0
            Notification.create(message: "Acidez está maior do que o ideal no", type_message: "danger", tank_id: tank.id)
          end

        else

          if ammonia < 0
            Notification.create(message: "Amonia está menor do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Amonia está menor do que o ideal no"
          end

          if ammonia > 0
            Notification.create(message: "Amonia está maior do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Amonia está maior do que o ideal no"
          end

          if temperature < 0
            Notification.create(message: "Temperatura está menor do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Temperatura está menor do que o ideal no"
          end
          if temperature < 0
            Notification.create(message: "Temperatura está maior do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Temperatura está maior do que o ideal no"
          end

          if oxigen < 0
            Notification.create(message: "Oxigenio está menor do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Oxigenio está menor do que o ideal no"
          end
          if oxigen < 0
            Notification.create(message: "Oxigenio está maior do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Oxigenio está maior do que o ideal no"
          end

          if ph < 0
            Notification.create(message: "PH está menor do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "PH está menor do que o ideal no"
          end
          if ph < 0
            Notification.create(message: "PH está maior do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "PH está maior do que o ideal no"
          end

          if acidity < 0
            Notification.create(message: "Acidez está menor do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Acidez está menor do que o ideal no"
          end
          if acidity < 0
            Notification.create(message: "Acidez está maior do que o ideal no", type_message: "danger", tank_id: tank.id) unless Notification.last.tank_id == tank.id && Notification.last.message == "Acidez está maior do que o ideal no"
          end
        end
      end
    end
  end

  private

  def redirect_perfil
    if user_signed_in?
      if current_user.perfil_id != 1
        redirect_to dashboards_path
        flash[:error] = "Você não pode acessar essa URL"
      end
    end
  end

  def set_ambiental_condition
    @ambiental_condition = AmbientalCondition.find(params[:id])
  end

  def ambiental_condition_params
    params.require(:ambiental_condition).permit(:ideal_temperature, :ideal_oxigen, :ideal_ph, :ideal_ammonia, :ideal_acidity, :specie_id)
  end
end

app/helpers/ambiental_conditions_helper.rb
module AmbientalConditionsHelper
end

app/views/ambiental_conditions/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Criar Condição Ambiental</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Condição Ambiental</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">cadastrar</a>
          </li>
        </ul>
      </div>
      <div class="tile">

        <%= simple_form_for(@ambiental_condition) do |f| %>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :ideal_temperature, input_html: {class: "form-control"}, label: "Temperatura Ideal", error: "Temperatura Ideal não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :ideal_oxigen, input_html: {class: "form-control"}, label: "Oxigênio Ideal", error: "Oxigênio Ideal não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :ideal_ph, input_html: {class: "form-control"}, label: "PH Ideal", error: "PH Ideal não pode ficar em branco" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :ideal_ammonia, input_html: {class: "form-control"}, label: "Amônia Ideal", error: "Amônia Ideal não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :ideal_acidity, input_html: {class: "form-control"}, label: "Acidez Ideal", error: "Acidez Ideal não pode ficar em branco" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= f.association :specie, input_html: {class: "form-control"}, include_blank: "Selecione", label: "Espécie", error: "Espécie não pode ficar em branco" %>
              </div>
            </div>
          </div>


          <div class="row">
            <div class="col-md-12">
              <%= button_tag(type: "submit", class: "btn btn-primary pull-right") do %>
                <i class="fa fa-save"></i>
                <span>Salvar</span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/ambiental_conditions/edit.html.erb
<h1>Editing Ambiental Condition</h1>

<%= render 'form', ambiental_condition: @ambiental_condition %>

<%= link_to 'Show', @ambiental_condition %> |
<%= link_to 'Back', ambiental_conditions_path %>

app/views/ambiental_conditions/index.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Listar Condições Ambientais</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Condições Ambientais</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">listar</a>
          </li>
        </ul>
      </div>

      <div class="tile">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Temperatura Ideal</th>
            <th>Oxigenio Ideal</th>
            <th>PH Ideal</th>
            <th>Amonia Ideal</th>
            <th>Acidez Ideal</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @ambiental_conditions.each do |ambiental_condition| %>
            <tr>
              <td><%= ambiental_condition.ideal_temperature %></td>
              <td><%= ambiental_condition.ideal_oxigen %></td>
              <td><%= ambiental_condition.ideal_ph %></td>
              <td><%= ambiental_condition.ideal_ammonia %></td>
              <td><%= ambiental_condition.ideal_acidity %></td>
              <td>
                <%= link_to "<i class='fa fa-edit'></i><span> Editar</span>".html_safe, edit_ambiental_condition_path(ambiental_condition), class: "btn btn-outline-primary" %>
                <%= link_to "<i class='fa fa-trash'></i><span> Excluir</span>".html_safe, ambiental_condition, method: :delete, data: {confirm: "Você tem certeza?"}, class: "btn btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/ambiental_conditions/new.html.erb
<h1>New Ambiental Condition</h1>

<%= render 'form', ambiental_condition: @ambiental_condition %>

<%= link_to 'Back', ambiental_conditions_path %>

app/views/ambiental_conditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ideal temperature:</strong>
  <%= @ambiental_condition.ideal_temperature %>
</p>

<p>
  <strong>Ideal oxigen:</strong>
  <%= @ambiental_condition.ideal_oxigen %>
</p>

<p>
  <strong>Ideal ph:</strong>
  <%= @ambiental_condition.ideal_ph %>
</p>

<p>
  <strong>Ideal ammonia:</strong>
  <%= @ambiental_condition.ideal_ammonia %>
</p>

<p>
  <strong>Ideal acidity:</strong>
  <%= @ambiental_condition.ideal_acidity %>
</p>

<%= link_to 'Edit', edit_ambiental_condition_path(@ambiental_condition) %> |
<%= link_to 'Back', ambiental_conditions_path %>