config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :water_sensors
  resources :solo_sensors
  resources :monitoring_histories
  resources :tanks
  resources :food_species
  resources :foods
  resources :food_types
  resources :ambiental_conditions
  resources :dashboards, only: :index
  scope :admin do
    get "/", to: "admin#index", as: "alarms"
    get "/new", to: "admin#new", as: "new_alarm"
    get "/:id", to: "admin#edit", as: "edit_alarm"
    post "/", to: "admin#create"
    patch ".:id", to: "admin#update"
  end
  get "/users/new", to: "users#new"
  get "/users", to: "users#index"
  get "/species", to: "species#index", as: "species"
  get "/species/new", to: "species#new", as: "new_specie"
  get "/species/edit/:id", to: "species#edit", as: "edit_species"
  post "/species", to: "species#create"
  patch "/species.:id", to: "species#update"
  delete "/species.:id", to: "species#destroy"
  post "/tanks/find_date", to: "tanks#find_date"
  post "/ambiental_conditions/calc", to: "ambiental_conditions#calculate"
  post "/notifications/update_view/:id", to: "notifications#update_view"
  post "/dashboards/ambiental_condition_values", to: "dashboards#get_ambiental_condition_values"
  post "/dashboards/tank_values", to: "dashboards#get_tank_values"
  post "/dashboards/ambiental_and_tank_values", to: "dashboards#get_difference_between_ambiental_condition_and_tank_values"
  post "/feed/:id", to: "tanks#feed"
  post "/check_alarms", to: "admin#catch_alarm"
  post "/dados_diarios", to: "tanks#insert_diary_data"
  post "/users/create", to: "users#create"
  redirect("/users/sign_in")

  authenticate :user do
    root to: "dashboards#index"
  end
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :alarm_type
end

app/models/alarm_type.rb
class AlarmType < ApplicationRecord
  has_many :alarms

  def to_s
    description
  end
end

app/models/ambiental_condition.rb
class AmbientalCondition < ApplicationRecord
  validates :ideal_acidity, presence: true
  validates :ideal_temperature, presence: true
  validates :ideal_oxigen, presence: true
  validates :ideal_ammonia, presence: true
  validates :ideal_ph, presence: true

  belongs_to :specie


  def to_s
    "temp: #{ideal_temperature} - O²: #{ideal_oxigen} - amonia: #{ideal_ammonia} - acidez: #{ideal_acidity}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_specie.rb
class FoodSpecie < ApplicationRecord
  belongs_to :food_type

  validates :name, presence: true
  validates :composition, presence: true
  validates :food_quantity, presence: true

  def to_s
    name
  end
end

app/models/food_type.rb
class FoodType < ApplicationRecord
  validates :description, presence: true

  def to_s
    description
  end
end

app/models/monitoring_history.rb
class MonitoringHistory < ApplicationRecord
  belongs_to :tank

  validates :liming, presence: true
  validates :oxigen, presence: true
  validates :ph, presence: true
  validates :quantitiy_food_daily, presence: true
  validates :quantity_fetilizing, presence: true
  validates :monitoring_date, presence: true

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :tank
end

app/models/perfil.rb
class Perfil < ApplicationRecord
  def to_s
    description
  end
end

app/models/solo_sensor.rb
class SoloSensor < ApplicationRecord
  belongs_to :tank
end

app/models/specie.rb
class Specie < ApplicationRecord
  belongs_to :food_specie
  has_one :ambiental_condition

  include RemoveSpecialCharacters

  validates :specie_name, presence: true
  validates :price, presence: true
  validates :weight, presence: true

  validate :no_price

  def to_s
    specie_name
  end

  def no_price
    errors.add(:price, "Valor R$0,00 não pode ser adicionado") if price == "000"
  end

end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :user
  belongs_to :specie

  has_many :notifications

  include RemoveSpecialCharacters

  validates :population_date, presence: true
  validates :initial_quantity, presence: true

  def to_s
    tank_type
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :perfil

  def to_s
    cpf
  end

end

app/models/water_sensor.rb
class WaterSensor < ApplicationRecord
  belongs_to :tank
end

app/controllers/monitoring_histories_controller.rb
class MonitoringHistoriesController < ApplicationController
  before_action :set_monitoring_history, only: [:show, :edit, :update, :destroy]
  before_action :redirect_perfil

  def index
    @monitoring_histories = MonitoringHistory.all
  end

  def show; end

  def new
    @monitoring_history = MonitoringHistory.new
  end

  def edit; end

  def create
    @monitoring_history = MonitoringHistory.new(monitoring_history_params)

    respond_to do |format|
      if @monitoring_history.save
        flash[:success] = "Cadastrado com sucesso"
        format.html {redirect_to monitoring_histories_path}
        format.json {render :show, status: :created, location: @monitoring_history}
      else
        flash[:error] = "Verifique os campos"
        format.html {render :new}
        format.json {render json: @monitoring_history.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @monitoring_history.update(monitoring_history_params)
        flash[:success] = "Editado com sucesso"
        format.html {redirect_to monitoring_histories_path}
        format.json {render :show, status: :ok, location: @monitoring_history}
      else
        flash[:error] = "Verifique os campos"
        format.html {render :edit}
        format.json {render json: @monitoring_history.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @monitoring_history.destroy
        flash[:success] = "Excluído com sucesso"
        format.html {redirect_to monitoring_histories_path}
        format.json {head :no_content}
      else
        flash[:error] = "Está relacionado em outra tabela"
        format.html {redirect_to monitoring_histories_path}
        format.json {head :no_content}
      end
    end
  end

  private

  def redirect_perfil
    if user_signed_in?
      if current_user.perfil_id != 1
        redirect_to dashboards_path
        flash[:error] = "Você não pode acessar essa URL"
      end
    end
  end

  def set_monitoring_history
    @monitoring_history = MonitoringHistory.find(params[:id])
  end

  def monitoring_history_params
    params.require(:monitoring_history).permit(:tank_id, :monitoring_date, :ph, :oxigen, :liming, :quantity_fetilizing, :quantitiy_food_daily, :disease, :procedimentos)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    notification = ''
    [:success, :info, :warning, :error].each do |type|
      if flash[type]
        notification += "<script>notification('#{type}', '#{flash[type]}');</script>"
      end
    end
    notification.html_safe
  end

end

app/helpers/food_species_helper.rb
module FoodSpeciesHelper
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/monitoring_histories_helper.rb
module MonitoringHistoriesHelper
end

app/helpers/solo_sensors_helper.rb
module SoloSensorsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/monitoring_histories/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Adicionar Dados Para o Monitoramento</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Monitoramento></li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">cadastrar</a>
          </li>
        </ul>
      </div>
      <div class="tile">
        <%= simple_form_for(@monitoring_history) do |f| %>

          <div class="row">
            <div class="col-md-5">
              <div class="form-group">
                <%= f.association :tank, input_html: {class: "form-control"}, include_blank: "Selecione", label: "Tanque", error: "Tanque não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-5">
              <div class="form-group">
                <%= f.input :monitoring_date, input_html: {class: "form-control"}, label: "Data de Monitoramento", error: "Data de Monitoramento não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-2">
              <div class="form-group">
                <%= f.input :ph, input_html: {class: "form-control"}, label: "PH", error: "PH não pode ficar em branco" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :oxigen, input_html: {class: "form-control"}, label: "Oxigênio", error: "Oxigênio não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :liming, input_html: {class: "form-control"}, label: "Calagem", error: "Colagem não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :quantity_fetilizing, input_html: {class: "form-control"}, label: "Quantidade de Fertilizante", error: "Quantidade de Fertilizante não pode ficar em branco" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :quantitiy_food_daily, input_html: {class: "form-control"}, label: "Quantidade de Ração Diária", error: "Quantidade de Ração Diária não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :disease, input_html: {class: "form-control"}, label: "Doenças", error: "não pode ficar em branco" %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :procedimentos, input_html: {class: "form-control"}, label: "Procedimentos", error: "não pode ficar em branco" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= button_tag(type: "submit", class: "btn btn-primary pull-right") do %>
                <i class="fa fa-save"></i>
                <span>Salvar</span>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/monitoring_histories/edit.html.erb
<h1>Editing Monitoring History</h1>

<%= render 'form', monitoring_history: @monitoring_history %>

<%= link_to 'Show', @monitoring_history %> |
<%= link_to 'Back', monitoring_histories_path %>

app/views/monitoring_histories/index.html.erb
<div class="row">
  <div class="col-md-12">
    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> Listar Monitoramentos</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Monitoramentos</li>
          <li class="breadcrumb-item">
            <a href="#" class="a_black">listar</a>
          </li>
        </ul>
      </div>

      <div class="tile">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Tanque</th>
            <th>Data de Monitoramento</th>
            <th>PH</th>
            <th>Oxigênio</th>
            <th>Colagem</th>
            <th>Quantidade de Fertilizante</th>
            <th>Quantidade de Comida Diária</th>
            <th>Doenças</th>
            <th>Procedimentos</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @monitoring_histories.each do |monitoring_history| %>
            <tr>
              <td><%= monitoring_history.tank %></td>
              <td><%= monitoring_history.monitoring_date %></td>
              <td><%= monitoring_history.ph %></td>
              <td><%= monitoring_history.oxigen %></td>
              <td><%= monitoring_history.liming %></td>
              <td><%= monitoring_history.quantity_fetilizing %></td>
              <td><%= monitoring_history.quantitiy_food_daily %></td>
              <td><%= monitoring_history.disease %></td>
              <td><%= monitoring_history.procedimentos %></td>
              <td>
                <%= link_to "<i class='fa fa-edit'></i><span> Editar</span>".html_safe, edit_monitoring_history_path(monitoring_history), class: "btn btn-outline-primary" %>
                <%= link_to "<i class='fa fa-trash'></i><span> Excluir</span>".html_safe, monitoring_history, method: :delete, data: {confirm: "Você tem certeza?"}, class: "btn btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/monitoring_histories/new.html.erb
<h1>New Monitoring History</h1>

<%= render 'form', monitoring_history: @monitoring_history %>

<%= link_to 'Back', monitoring_histories_path %>

app/views/monitoring_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tank:</strong>
  <%= @monitoring_history.tank %>
</p>

<p>
  <strong>Monitoring date:</strong>
  <%= @monitoring_history.monitoring_date %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @monitoring_history.ph %>
</p>

<p>
  <strong>Oxigen:</strong>
  <%= @monitoring_history.oxigen %>
</p>

<p>
  <strong>Liming:</strong>
  <%= @monitoring_history.liming %>
</p>

<p>
  <strong>Quantity fetilizing:</strong>
  <%= @monitoring_history.quantity_fetilizing %>
</p>

<p>
  <strong>Quantitiy food daily:</strong>
  <%= @monitoring_history.quantitiy_food_daily %>
</p>

<p>
  <strong>Disease:</strong>
  <%= @monitoring_history.disease %>
</p>

<p>
  <strong>Procedimentos:</strong>
  <%= @monitoring_history.procedimentos %>
</p>

<%= link_to 'Edit', edit_monitoring_history_path(@monitoring_history) %> |
<%= link_to 'Back', monitoring_histories_path %>